Implented event media upload with Multer.
UBC-Product-Management-Club/pmc-portal-be pull request #11
Opened 2024-08-10 19:34 UTC by tobyL05

WARNING: Adding events with media will also add the images to firebase storage. When deleting an event, remember to delete the images from firebase storage too. (will probably need to fix this later on).

TLDR:
- Used FormData to send media along with event details to upload an event.
1. Media is first uploaded to Firebase storage
2. Download links for each piece of media is generated
3. Each download links are added to the "media" field in the event document. 

- Moved the Event and Attendee types to Schema folder for consistency
- Edited the Event type since FormData only allows strings. Correct types are enforced before uploading to firestore

2024-08-12 00:24 UTC, Hgjnnf requested changes
Works pretty well! I added some comments.

2024-08-12 00:24 UTC, Hgjnnf commented on src/routes/event.ts
> +    } = JSON.parse(JSON.stringify(req.body))
For this one, I was thinking we could stringify the JSON in the frontend so that we can just parse it in the backend instread of JSON.parse(JSON.stringify(req.body)).

2024-08-12 00:24 UTC, Hgjnnf commented on src/routes/event.ts
> -    if (!name || !date || !location || !description || !media || !member_price || !non_member_price || !attendees || member_only == undefined) {
we should keep this for checking

2024-08-12 08:14 UTC, tobyL05 commented on src/routes/event.ts
> +    } = JSON.parse(JSON.stringify(req.body))
I think we can do that later on when we have our own frontend. On Postman, the data is currently being sent like this. This is the most intuitive imo
![image](https://github.com/user-attachments/assets/34341ace-f677-4df2-84cb-45855c60ce10)

2024-08-12 08:52 UTC, tobyL05 commented on src/index.ts
> +// app.use(express.json());
Fixed. I added it back and looks like all the endpoints work.

2024-08-12 08:55 UTC, tobyL05 commented on src/routes/event.ts
> -    if (!name || !date || !location || !description || !media || !member_price || !non_member_price || !attendees || member_only == undefined) {
Kept the conditional but added check to see if media array is empty (no media uploaded)

2024-08-12 08:57 UTC, tobyL05 commented on src/routes/index.ts
> -apiRouter.use("/attendee", attendeeRouter)
Brought the original routes back. I guess we can keep it that way for development. We'll need middleware for some routes in the future (e.g. /profile so users can only access their own profile and can't access others)

2024-08-13 04:37 UTC, Hgjnnf approved these changes
Nice! Let's merge this

2024-08-13 05:00 UTC, merged