Added events registration, including attendee, GET and POST methods
UBC-Product-Management-Club/pmc-portal-be pull request #9
Opened 2024-07-24 07:24 UTC by karenagustino

When a member/non-member wants to register for an event, they'll go to the event page (which is also created here) and click register. After clicking "register", the backend will create a new Attendee associated with that purchase (it keeps the associated event_Id). If they are a member, they'll keep their member_id from the user collection in the database.

To test this:
Go to PostMan >> POST method >> insert either links: 
localhost:8000/api/v1/event/addEvent
localhost:8000/api/v1/attendee/addAttendee

Under the dropdown for Params in PostMan >> Go to Body >> raw >> Input a random JSON file based on the variables of events or attendees collection

For example: 
{
    "is_member": "false",
    "member_Id": "pRQouM9aHtQRZQtBzYySZqfs7Wf2",
    "event_Id": "12345 some event id"
}

2024-07-25 00:13 UTC, Hgjnnf requested changes

2024-07-25 00:13 UTC, Hgjnnf commented on src/routes/attendee.ts
> +    const { is_member, member_Id, event_Id } = req.body;
update the new fields here as well

2024-07-27 04:36 UTC, gordoHWC commented on package.json
>      "jest": "^29.7.0",
missing a comma here

2024-07-27 04:36 UTC, gordoHWC commented on src/routes/attendee.ts
> +        await addAttendee(attendee_Id, newAttendee, event_Id);
since attendee_Id and event_Id are in newAttendee already, we don't need to pass this in twice

2024-07-27 04:36 UTC, gordoHWC commented on src/routes/attendee.ts
> +    const newAttendee: Attendee = { attendee_Id, is_member, member_Id, event_Id, first_name, last_name, student_num, email, year_level, major, faculty, familiarity, found_out, dietary };
we can simplify this code since the req.body already has everything but attendee_Id. We could do:
```suggestion
    const newAttendee: Attendee = { attendee_Id, ...req.body };
```

2024-07-27 04:36 UTC, gordoHWC commented on src/routes/attendee.ts
> +    for (const field of requiredFields) {
we should also check if (member_Id is not empty and member_Id exists) in the database and if event_Id exists in the database. Also, member_Id could be optional, so some might have empty member_Id, which won't pass the test here. We can remove member_Id from the array of required fields

2024-07-27 04:36 UTC, gordoHWC commented on src/routes/event.ts
> +    const { name, date, location, description, media, price, attendees, member_only } = req.body;
we should have both member_price and non_member_price

2024-07-27 04:36 UTC, gordoHWC commented on src/routes/event.ts
> +    if (!name || !date || !location || !description || !media || !price || !attendees || !member_only) {
member_only doesn't work if it is false. We can instead check if it is undefined

2024-07-27 04:37 UTC, gordoHWC requested changes
need to change some small details; but it mostly looks good

2024-07-27 07:21 UTC, tobyL05 commented on src/routes/attendee.ts
> +attendeeRouter.get('/attendee/:eventId', async (req, res) => {
I think there's an extra "/attendee". The path right now would be "/attendee/attendee/:eventId"

2024-07-27 23:09 UTC, Hgjnnf commented on src/routes/attendee.ts
> +attendeeRouter.get('/attendee/:eventId', async (req, res) => {
Yep, thanks for catching it!

2024-08-04 07:25 UTC, Hgjnnf approved these changes
Add event and add attendee endpoints look good! There are still some issues with the GET endpoints and some work need to do to clean up the code (reach out to me if you want to learn more about these :)) Let's merge it for now, great work!

2024-08-06 02:46 UTC, merged